inherit_from: .rubocop_todo.yml
AllCops:
  Include:
    - Gemfile
    - lib/**/*.rake
  Exclude:
    - pkg/**
    - bin/**
    - bundle_bin/**
StringLiterals:
  EnforcedStyle: single_quotes
# Configuration parameters: AllowURI, URISchemes.
Metrics/LineLength:
  Max: 120
Style/Documentation:
  Enabled: false
